// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc7CRYTrFsey0eupnGGPOAvYQV0WeDZl4',
    appId: '1:761607880346:web:c8a7ea325e056393fba923',
    messagingSenderId: '761607880346',
    projectId: 'eventopya-9e643',
    authDomain: 'eventopya-9e643.firebaseapp.com',
    storageBucket: 'eventopya-9e643.appspot.com',
    measurementId: 'G-BN3JDJLRTY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVfOt8sqFdCkjcFClgaTzgQ5ddcHG0XoI',
    appId: '1:761607880346:android:cdc9f1b43a1423e3fba923',
    messagingSenderId: '761607880346',
    projectId: 'eventopya-9e643',
    storageBucket: 'eventopya-9e643.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9mScF1kvSnk7K-q97KFxqhY1ftPa21xU',
    appId: '1:761607880346:ios:66e8a10c0424c9d8fba923',
    messagingSenderId: '761607880346',
    projectId: 'eventopya-9e643',
    storageBucket: 'eventopya-9e643.appspot.com',
    iosClientId: '761607880346-kf5fha0e040r66iig962h6js79titj6e.apps.googleusercontent.com',
    iosBundleId: 'com.example.weddingOrganise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9mScF1kvSnk7K-q97KFxqhY1ftPa21xU',
    appId: '1:761607880346:ios:66e8a10c0424c9d8fba923',
    messagingSenderId: '761607880346',
    projectId: 'eventopya-9e643',
    storageBucket: 'eventopya-9e643.appspot.com',
    iosClientId: '761607880346-kf5fha0e040r66iig962h6js79titj6e.apps.googleusercontent.com',
    iosBundleId: 'com.example.weddingOrganise',
  );
}
